language: node_js
install:
    - npm install -g yarn
    - yarn install
    - yarn global add browserify
    - cd client && yarn install && cd ..
script:
    - yarn run lint
    - cd client && yarn run lint && yarn run build
